---
- name: "Check if vhost exists for {{ vhost.domain }}"
  ansible.builtin.stat:
    path: "/etc/nginx/{{ (ansible_distribution in ['Ubuntu', 'Debian']) | ternary('sites-available/' + vhost.domain, 'conf.d/' + vhost.domain + '.conf') }}"
  register: nginx_vhost

- name: "Make sure ipv6_addr exists"
  ansible.builtin.set_fact:
    new_vhost: "{{ {'ipv6_addr': '::'} | combine(vhost) }}"

- name: "Add the ipv6 address {{ vhost.ipv6_addr }} for {{ vhost.domain }}"
  ansible.builtin.include_tasks: add_ipv6_address.yaml
  when:
    - "new_vhost.ipv6_addr != '::'"
    - "new_vhost.ipv6_addr not in ansible_facts['all_ipv6_addresses']"

- name: "Create vhost {{ new_vhost.domain }}"
  ansible.builtin.include_tasks: create-vhost.yaml
  when: not nginx_vhost.stat.exists

- name: "Enable nginx vhost {{ new_vhost.domain }}"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ new_vhost.domain }}"
    dest: "/etc/nginx/sites-enabled/{{ new_vhost.domain }}"
    state: link
  when: "ansible_distribution in ['Ubuntu', 'Debian']"
  become: true

- name: "Test nginx configuration"
  ansible.builtin.command: nginx -t
  become: true
  notify: "Reload nginx"
  changed_when: false
