---
- name: "Create nginx vhost for {{ new_vhost.domain }}"
  ansible.builtin.template:
    src: "vhost.conf.j2"
    dest: "/etc/nginx/{{ (ansible_distribution in ['Ubuntu', 'Debian']) | ternary('sites-available/' + vhost.domain, 'conf.d/' + vhost.domain + '.conf') }}"
    mode: "0644"
  when:
    - "not nginx_vhost.stat.exists"
  become: true

- name: "Configure DNS"
  community.general.cloudflare_dns:
    zone: "{{ zone }}"
    record: "{{ new_vhost.domain.split('.')[-3] }}"
    type: AAAA
    value: "{{ new_vhost.ipv6_addr }}"
    proxied: false
    api_token: "{{ nginx_cf_token[zone] }}"
  when: 
    - "new_vhost.ipv6_addr != '::'"
    - "'adjust_cf_dns' in new_vhost"
    - "new_vhost.adjust_cf_dns"
