---
- name: "Get a list of all existing vhosts"
  ansible.builtin.find:
    paths: /etc/nginx/{{ (ansible_distribution in ['Ubuntu', 'Debian']) | ternary('sites-available/', 'conf.d/') }}
    file_type: any
    recurse: false
  register: existing_vhosts_obj

- name: "Transform existing and defined vhosts into compareable format"
  ansible.builtin.set_fact:
    defined_vhosts: "{{ nginx_vhosts | map(attribute='domain') | list }}"
    existing_vhosts: "{{ existing_vhosts_obj.files | map(attribute='path') | map('basename') | list }}"

- name: "Extend list of existing vhosts by .conf extension on rhel based systems"
  ansible.builtin.set_fact:
    defined_vhosts_with_conf: "{{ defined_vhosts | map('regex_replace', '$', '.conf') | list }}"
  when:
    - ansible_distribution not in ['Ubuntu', 'Debian']

- name: "Disable nginx vhosts which are no longer present in the ansible inventory"
  ansible.builtin.file:
    path: "/etc/nginx/sites-available/{{ item }}"
    state: absent
  when:
    - "ansible_distribution in ['Ubuntu', 'Debian']"
  loop: "{{ existing_vhosts | difference(defined_vhosts) }}"
  become: true
  notify: "Reload nginx"

- name: "Delete nginx vhosts which are no longer present in the ansible inventory"
  ansible.builtin.file:
    path: "/etc/nginx/sites-available/{{ item }}"
    state: absent
  when:
    - "ansible_distribution in ['Ubuntu', 'Debian']"
  loop: "{{ existing_vhosts | difference(defined_vhosts) }}"
  become: true

- name: "Delete nginx vhosts which are no longer present in the ansible inventory"
  ansible.builtin.file:
    path: "/etc/nginx/conf.d/{{ item }}"
    state: absent
  when: 
    - "ansible_distribution not in ['Ubuntu', 'Debian']"
  loop: "{{ existing_vhosts | difference(defined_vhosts_with_conf) }}"
  become: true

- name: "Delete certificates of nginx vhosts which are no longer present in the ansible inventory"
  ansible.builtin.file:
    path: "/root/.acme.sh/{{ item }}_ecc/"
    state: absent
  loop: "{{ existing_vhosts | difference(defined_vhosts) }}"
  become: true
