---
- name: "Install requirements"
  ansible.builtin.package:
    name:
      - curl
      - tar
      - "{{ (ansible_pkg_mgr == 'apt') | ternary('cron', 'cronie') }}"
    state: present
  become: true

- name: Install acme.sh
  ansible.builtin.command: "sh -c 'curl https://get.acme.sh | sh -s email={{ nginx_cert_email }}'"
  become: true

- name: Create crontab for acme.sh
  ansible.builtin.cron:
    name: "acmesh"
    minute: "{{ 59 | random(seed=inventory_hostname) }}"
    hour: "{{ 23 | random(seed=inventory_hostname) }}"
    job: "/bin/bash /root/.acme.sh/acme.sh --cron --home /root/.acme.sh &> /dev/null"
  become: true

- name: Set lets encrypt backend for acme.sh
  ansible.builtin.command: |
    /root/.acme.sh/acme.sh --server "https://acme-v02.api.letsencrypt.org/directory" --set-default-ca
  become: true
