---
- name: "Check if private key exists"
  ansible.builtin.stat:
    path: "/root/.acme.sh/{{ vhost.domain }}_ecc/{{ vhost.domain }}.key"
  register: nginx_vhost_certificates_key
  become: true

- name: "Check if fullchain certificate exists"
  ansible.builtin.stat:
    path: "/root/.acme.sh/{{ vhost.domain }}_ecc/fullchain.cer"
  register: nginx_vhost_certificates_cer
  become: true

- name: "Issue certificate"
  when: not nginx_vhost_certificates_cer.stat.exists or
        not nginx_vhost_certificates_key.stat.exists
  block:
    - name: "Set splitted domain as fact next tasks"
      ansible.builtin.set_fact:
        splitted: "{{ vhost.domain.split('.') }}"

    - name: "Set dns zone as fact for credential selection"
      ansible.builtin.set_fact:
        zone: "{{ splitted[-2] }}.{{ splitted[-1] }}"

    - name: "Issue certificate"
      # the usage of shell is required to pass environment variables
      ansible.builtin.shell: "/root/.acme.sh/acme.sh --issue --keylength ec-384 --dns dns_cf -d {{ vhost.domain }}"
      environment:
        CF_Token: "{{ nginx_cf_token[zone] }}"
      when: not nginx_vhost_certificates_cer.stat.exists or
            not nginx_vhost_certificates_key.stat.exists
      become: true