---
- name: "Install nginx"
  ansible.builtin.include_tasks: install-nginx.yaml

- name: "Hide nginx version in http banner by setting server_tokens directive to off in nginx configuration"
  when:
    - "nginx_hide_server_tokens"
  ansible.builtin.lineinfile:
    path: "/etc/nginx/nginx.conf"
    regexp: '^(\s*)# server_tokens off;'
    line: '\1server_tokens off;'
    backrefs: true  # enables \1
  notify: "Reload nginx"
  become: true

- name: "Iptables: Allow http and https"
  when:
    - "nginx_iptables"
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports: [80, 443]
    jump: ACCEPT
    ip_version: "{{ item }}"
  become: true
  with_items: [ipv4, ipv6]

- name: "Handle absent vhosts"
  ansible.builtin.include_tasks: handle-absent.yaml

- name: "Create vhosts"
  ansible.builtin.include_tasks: create-vhosts.yaml
  loop: "{{ nginx_vhosts | default([]) }}"
  vars:
    vhost: "{{ item }}"
