---
- name: "Restart nginx"
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  become: true

- name: "Reload nginx"
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  become: true
